name: Python SSL Checker Tests

on:
  push:
    branches: 
      - '*'
  pull_request: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test the script
      run: |
        python ssl_checker.py -h
    - name: Test a host
      run: |
        python ssl_checker.py -H google.com
    - name: Test JSON output
      run: |
        python ssl_checker.py -H google.com -j
    - name: Test read list from file
      run: |
        echo -e "google.com\ntwitter.com" > list
        python ssl_checker.py -f list
    - name: Test CSV output
      run: |
        python ssl_checker.py -H google.com -c test.csv
    - name: Test JSON file output
      run: |
        python ssl_checker.py -H google.com twitter.com -J
    - name: Test with port
      run: |
        python ssl_checker.py -H google.com:443
    - name: Test summary output
      run: |
        python ssl_checker.py -H google.com -S
    - name: Test HTML export
      run: |
        python ssl_checker.py -H google.com -x
